platform :ios, '15.0'

target 'App' do
  capacitor_pods
  # No se necesitan pods adicionales - CoreLocation es nativo de iOS
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '15.0'
      config.build_settings['SWIFT_VERSION'] = '5.0'
    end
  end
end
